### ISSUE TITLE
location

### ISSUE THREAD

**Issue by mbutler808** [cusisom/cusimano-rclass-project#2]
https://github.com/cusisom/cusimano-rclass-project/blob/7703c4d966d7ba12900fa1ad9e2a86cba408e5dd/Code/Processing_code/processingcode.R#L236

Good! But save this in the **processed data folder** by setting the proper relative path. Each dictionary should be together with its data file. 

Also, hand editing is OK but why not try to create the dictionary with your code by subsetting the original dictionary file?

**Comment by cusisom** [comment]
This has been updated along with the other needed outputs.
