### ISSUE TITLE
Project 1 assessment

### ISSUE THREAD

**Issue by mbutler808** [cusisom/cusimano-rclass-project#3]
# Project Rubric

Your audience is the user, members of the general public who may want to use your data and/or code. To be useful, your code and documentation must be clear to naive users (people familiar with R, but not with this project). 

Elements:
1. Your github repo, organized following the project template.
2. Your modified code, quarto, and README files, organized in the repo.
2. Your output files (any requested output, i.e., `.csv`, `.html`, `.docx`, `.pdf` files) in their proper places in the repo.

|Criteria| Evaluation| Scoring | Points | Comments |
|:---------|:---|:---|:---|:---|
|__Right__| Code runs without Error - Must be YES | 0/10 | 10 ||
|	  | Code produces correct output | 0-5 | 2 |Very nice code, but forgot to include code to produce output|
|__Readable__| Code is readable (good use of white space, etc.) |0-5| 2 ||
|        | Code is understandable (good naming conventions, concise informative comments) |||clean but comments have to do with data analysis, do not explain code. Will you understand this script a year from now? |
|__Reproducible__| READMEs document project organization | 0-5| 3| ok |
|        | READMEs list contents of each directory | || missing |
|        | READMEs explain the order to run the code/quarto in order to reproduce analysis| || not clearly indicated|
|__Aesthetics__| Files are free of unnecessary clutter (assignment instructions, etc.) | 0-5 | 3 | READMEs not updated for a public repo|
|        | Code is elegant (not required, but a bonus) |  | | nice|
|__Bottom Line__| | 30 | 20 | very nice! Add output and update documentatiom for the code, and to be self-explanatory to the public. You can earn points back by fixing these issues for project 2.  |

**Comment by mbutler808** [comment]
You can see an example solution here: <https://github.com/mbutler808/Project-1-solution>

**Comment by cusisom** [comment]
I have worked on each of these issues. My outputs should all be in order at this point. I have updated my R script by removing much of the comments on analysis and adding more commentary on coding. I also updated all of my repository folders and the README files in each. I'm not 100% sure if it reads the way it should but I believe that it is an improvement on the first submission.

**Comment by mbutler808** [comment]
Nice Job Daniel!   Thanks for making the edits.  30/30
