### ISSUE TITLE
Error here

### ISSUE THREAD

**Issue by mbutler808** [cusisom/cusimano-rclass-project#4]
Hi Danny,

MUCH MUCH BETTER!  Very nice. 

You are still getting an error on this line that stops execution (which is bad):
```
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '../../Data/Raw_data/datadictionary2.0.csv': No such file or directory
```
https://github.com/cusisom/cusimano-rclass-project/blob/bae6f88b2685cfdfb688c3af2eb8c5325a5e28ae/Code/Processing_code/processingcode.R#L233

You are pointing to the raw data directory when reading in your new dictionary, and it is not there (`No such file or directory` error). Please fix and resubmit. 

M

**Comment by cusisom** [comment]
Thank you! I have debugged this issue and pushed it through to git.
